spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true # JPA 쿼리문을 로깅합니다.
    hibernate:
      ddl-auto: none # 엔티티에 따라 DDL 을 제어할 수 있습니다.(위험함 none 해야함)
    properties:
      hibernate:
        format_sql: true # JPA 쿼리문을 로깅을 이쁘게 합니다.

mybatis:
  type-aliases-package: com.mallang.crocodile # xml 파일 result type 에 패키지명을 생략할 수 있도록 alias 설정
  mapper-locations: mybatis/**/*.xml # mapper 파일 경로 설정
  configuration.map-underscore-to-camel-case: true # model 프로퍼티 camel case 설정

crocodile:
  allowed-referers:
      - http://localhost:8080
      - https://crocodile-production.up.raislway.app

logging:
  level:
    jdbc:
      sqlonly: off # SQL 문을 보여준다.
      sqltiming: debug # SQL 문과 이 SQL 문을 수행하는 시간(ms)을 같이 보여준다.
      resultsettable: off # ResultSet 을 제외한 모든 JDBC 호출 정보를 로그로 보여준다. 상당히 많은 양의 로그가 나오기 때문에 권장하지 않음.
      audit: off # ResultSet 을 포함한 모든 JDBC 호출 정보를 로그로 보여준다. audit 처럼 많은 로그가 나오기 때문에 권장하지 않음.
      resultset: off # SQL 의 결과로 조회된 데이터를 table 형태로 로그를 보여준다.
      connection: off # DB 연결, 연결 해제와 관련된 로그를 보여준다

# local
---
spring:
  config:
    activate:
      on-profile: local # 스프링부트를 띄울때 profile 이 local 이면 아래 설정을 따르도록 합니다.
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.99.100:3306/crocodile?characterEncoding=utf8
    username: root
    password: 1225